runtime: python310
entrypoint: pip install -r requirements.txt && streamlit run app.py --server.port $PORT --server.address 0.0.0.0

env_variables:
  DATABRICKS_INSTANCE: "https://adb-3149763786926783.3.azuredatabricks.net"
  DATABRICKS_TOKEN: "dapi43e078850b4849182ec31b98dd0bcde9"
  JOB_ID: "74322109913991"
  WAREHOUSE_ID: "471689e9733cf085"
  VOLUME_PATH: "/Volumes/dev_uc_catalog/default/zatca_invoice_check"
  ARCHIVE_PATH: "/Volumes/dev_uc_catalog/default/zatca_invoice_check_archive"
  MAIN_PASSWORD: "Password"
  FINANCE_PASSWORD: "Finance"
